# 데이터 살펴보기

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample = pd.read_csv('sample_submission.csv')

train.head()

id   Age    TypeofContact  CityTier  DurationOfPitch      Occupation  \
0   1  28.0  Company Invited         1             10.0  Small Business   
1   2  34.0     Self Enquiry         3              NaN  Small Business   
2   3  45.0  Company Invited         1              NaN        Salaried   
3   4  29.0  Company Invited         1              7.0  Small Business   
4   5  42.0     Self Enquiry         3              6.0        Salaried   

   Gender  NumberOfPersonVisiting  NumberOfFollowups ProductPitched  \
0    Male                       3                4.0          Basic   
1  Female                       2                4.0         Deluxe   
2    Male                       2                3.0         Deluxe   
3    Male                       3                5.0          Basic   
4    Male                       2                3.0         Deluxe   

   PreferredPropertyStar MaritalStatus  NumberOfTrips  Passport  \
0                    3.0       Married            3.0         0   
1                    4.0        Single            1.0         1   
2                    4.0       Married            2.0         0   
3                    4.0       Married            3.0         0   
4                    3.0      Divorced            2.0         0   

   PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting Designation  \
0                       1       0                       1.0   Executive   
1                       5       1                       0.0     Manager   
2                       4       1                       0.0     Manager   
3                       4       0                       1.0   Executive   
4                       3       1                       0.0     Manager   

   MonthlyIncome  ProdTaken  
0        20384.0          0  
1        19599.0          1  
2            NaN          0  
3        21274.0          1  
4        19907.0          0

In [4]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1955 entries, 0 to 1954
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   id                        1955 non-null   int64  
 1   Age                       1861 non-null   float64
 2   TypeofContact             1945 non-null   object 
 3   CityTier                  1955 non-null   int64  
 4   DurationOfPitch           1853 non-null   float64
 5   Occupation                1955 non-null   object 
 6   Gender                    1955 non-null   object 
 7   NumberOfPersonVisiting    1955 non-null   int64  
 8   NumberOfFollowups         1942 non-null   float64
 9   ProductPitched            1955 non-null   object 
 10  PreferredPropertyStar     1945 non-null   float64
 11  MaritalStatus             1955 non-null   object 
 12  NumberOfTrips             1898 non-null   float64
 13  Passport                  1955 non-null   int64  
 14  PitchSat

In [ ]:

for i in range(20):
    plt.subplot(20, 1, i)
    plt.plot(train[])

# 데이터 전처리

In [5]:
train.isna().sum()

# age float / typeofcontact objecct() / durationofpitch float(없을수도/평균) / numberoffollowups float(없을수도?평균?) / preferredpropertysstar float(평균)
# numberoftrips float(평균) / numberofchildrenvisiting float(없을수도/평균) / monthlyincome float(평균)

id                            0
Age                          94
TypeofContact                10
CityTier                      0
DurationOfPitch             102
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            13
ProductPitched                0
PreferredPropertyStar        10
MaritalStatus                 0
NumberOfTrips                57
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     27
Designation                   0
MonthlyIncome               100
ProdTaken                     0
dtype: int64

In [43]:
na = train.isna().sum()

col = na[na>0].keys()
col

Index(['Age', 'TypeofContact', 'DurationOfPitch', 'NumberOfFollowups',
       'PreferredPropertyStar', 'NumberOfTrips', 'NumberOfChildrenVisiting',
       'MonthlyIncome'],
      dtype='object')

In [44]:
object_col = 'TypeofContact'
float_col = col.drop(object_col)
float_col

Index(['Age', 'DurationOfPitch', 'NumberOfFollowups', 'PreferredPropertyStar',
       'NumberOfTrips', 'NumberOfChildrenVisiting', 'MonthlyIncome'],
      dtype='object')

In [ ]:
trian[object_col] = 

In [16]:
all_col = train.keys()
all_col

Index(['id', 'Age', 'TypeofContact', 'CityTier', 'DurationOfPitch',
       'Occupation', 'Gender', 'NumberOfPersonVisiting', 'NumberOfFollowups',
       'ProductPitched', 'PreferredPropertyStar', 'MaritalStatus',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome',
       'ProdTaken'],
      dtype='object')

In [36]:
for idx, col in enumerate(all_col):
    val = train[col]
    print(col)
    print(val.unique())

id
[   1    2    3 ... 1953 1954 1955]
Age
[28. 34. 45. 29. 42. 32. 43. 36. 35. 31. 49. nan 52. 33. 22. 50. 23. 41.
 37. 40. 56. 54. 39. 20. 46. 27. 38. 25. 26. 24. 30. 21. 51. 47. 55. 44.
 53. 48. 18. 57. 60. 59. 19. 58. 61.]
TypeofContact
['Company Invited' 'Self Enquiry' nan]
CityTier
[1 3 2]
DurationOfPitch
[10. nan  7.  6. 29.  8. 20. 14.  9. 16. 15. 23. 21. 11. 25. 34. 17. 13.
 28. 12. 22. 30. 24. 27. 31. 35. 32. 33. 36. 19. 26. 18.  5.]
Occupation
['Small Business' 'Salaried' 'Large Business' 'Free Lancer']
Gender
['Male' 'Female' 'Fe Male']
NumberOfPersonVisiting
[3 2 4 1 5]
NumberOfFollowups
[ 4.  3.  5.  1.  6.  2. nan]
ProductPitched
['Basic' 'Deluxe' 'King' 'Standard' 'Super Deluxe']
PreferredPropertyStar
[ 3.  4.  5. nan]
MaritalStatus
['Married' 'Single' 'Divorced' 'Unmarried']
NumberOfTrips
[ 3.  1.  2.  7.  4.  6.  5.  8. nan 19.]
Passport
[0 1]
PitchSatisfactionScore
[1 5 4 3 2]
OwnCar
[0 1]
NumberOfChildrenVisiting
[ 1.  0.  2.  3. nan]
Designation
['Executive' 'Manag

In [38]:
train['Gender'] = train['Gender'].replace('Fe Male', 'Female')

train['Gender'].value_counts()

Male      1207
Female     748
Name: Gender, dtype: int64